name: Pnpm
on:
  workflow_call:
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
