name: Tests
on:
  push:
    branches:
      - main
jobs:
  unit-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: ./.github/workflows/workflow-2.yml
      - name: Run tests
        run: pnpm run test:coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
